spring.application.name=gestao_de_frotas_de_entrega

spring.datasource.url=jdbc:postgresql://localhost:5432/api_gestao_entrega
spring.datasource.username=postgres
spring.datasource.password=guigo2370

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true